# https://numtide.github.io/devshell

[devshell]
name = "NuttX"
motd = "Welcome to NuttX!"

[[commands]]
package = "cmake"

[[commands]]
package = "esptool"

[[commands]]
package = "gnumake"

# ARM might be easier...
# [[commands]]
# package = "gcc-arm-embedded-13"
